language: node_js
node_js: 12
cache:
  directories:
    - node_modules
  script:
    - npm install
    - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master

dist: bionic
sudo: false
